#AntiSignEdit - Original idea from MauriceBtK | https://www.spigotmc.org/resources/disable-edit-signs-1-0.110653/

#Updated by LucasInDev, sysadmin on CrowtyCraft Network - Join us! | https://crowtycraft.es

#Social links: https://go.crowtycraft.es/social
#Help & Support: https://help.crowtycraft.es
#TrustPilot: https://go.crowtycraft.es/trustpilot

#Play with us! : https://crowtycraft.es


#  WAAAAAAARNING, I HAVE A VERY BAD ENGLISH, SO... SORRY :/

config:
  #If the user or group has this permission, they will be able to edit signs
  permission: 'crowty.edit.sign'

  #Per-World settings
  enabled-worlds:
    enabled: false #Enable or disable per-world sign edit
    #This feature allow to edit signs in specified worlds if you need it
    #⚠️CAUTION:  If a user has the permission indicated above, they will be able to edit the poster even if they are in a world where it is prohibited
    worlds:
      - "World1"
      - "World2"
      - "World3"

  #Sound option
  sound:
    enabled: true #Enable or disable sound play on deny sign edit
    sound-type: BLOCK_CANDLE_EXTINGUISH #https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
  #If you want change this sound, check Spigot-API

  #Special effect section
  effects:
    enabled: false
    #This feature allow to send effect to player have been denied edit of a sign
    effect-type: BLINDNESS #https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html
    effect-duration: 40 #Value in Ticks, so value of: '20' is 1 second
  #If you want change this effect, check Spigot-API


  #Language section
  prefix: '&6&lCrowtyCraftNT'
  notify-nopermission: true #If set to 'false' nothing will be sent to the user
  nopermission: '&c&lHey! &7You dont have permission to edit this sign...'

#All about color codes (External website):  https://minecraftitemids.com/color-codes

#For message, it's better '§' to use color codes, it's a good practice of optimization, example: §6§lCrowtyCraftNT